name: Profile Metrics

on:
  schedule:
    # Runs on the 1st day of every month at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: alaminxtration
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Features
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_days: 14
          plugin_activity_filter: all
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          
          plugin_notable: yes
          plugin_notable_filter: stars:>500
          
          plugin_discussions: yes
